### ISSUE TITLE
Completer shortcut

### ISSUE THREAD

**Issue by snrcze** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#19]
Na macOS nejde zobrazit completer. Zkratka cmd+space je rezervovaná pro otevření Spotlightu.

**Comment by SonyPony** [comment]
Od verze 1.0.7 bude klávesová zkratka změněna na OS X na cmd+J

**Comment by thejoeejoee** [comment]
Release nahozen, jestliže funguje, @snrcze zavři issue prosím.
