### ISSUE TITLE
Podpora Windows

### ISSUE THREAD

**Issue by SonyPony** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#2]

**Comment by thejoeejoee** [comment]
Viz 2a2444ba3fb799e7df1f21dda8cf3c1d2f8b075c, vyzkoušej na Windows prosím.

**Comment by thejoeejoee** [comment]
@EnkeyMC otestoval:
- výchozí CMD neumí barvy, Powershell OK
- zběsilá chybová hláška při chybějícím cigwin.dll

**Comment by thejoeejoee** [comment]
Barvy pořešeny pomocí přídaného --no--color argumentu, taktéž přidána lepší podpora pro odchyt zacyklení/timeoutu. 

Ještě bych potřeboval alespoň jeden stroj, @SonyPony, @CaptainUnitato, @ivakavankova?

**Comment by thejoeejoee** [comment]
Manuálně vyzkoušeno u výše zmíněných.
