### ISSUE TITLE
Upozornění na chybu v hlavičce

### ISSUE THREAD

**Issue by snrcze** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#20]
Jen takový detail, když se zapomene vložit .IFJcode17. Ušetří to pár nervů hledání, kde je chyba, protože ji vyhodnotí na řádku "none". :)

**Comment by thejoeejoee** [comment]
Od `1.0.7` vylepšeny jak statické, tak běhové chybové hlášky, včetně chybějící hlavičky.

**Comment by thejoeejoee** [comment]
Release nahozen, stačí upgrade pomocí pip.
@snrcze jestli vše OK, zavři prosím.
