### ISSUE TITLE
Při uložení desetinného čísla do integeru IDE spadne

### ISSUE THREAD

**Issue by snrcze** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#21]
IDE padá, pokud do integeru uložím desetinné číslo.
Např.
DEFVAR GF@tmp1
MOVE GF@tmp1 int@1.1
WRITE GF@tmp1

**Comment by thejoeejoee** [comment]
Opraveno do `1.1.6`, vyzkoušíš si prosím po aktualizaci?

**Comment by thejoeejoee** [comment]
Zkontrolováno.
