### ISSUE TITLE
Řetězec

### ISSUE THREAD

**Issue by JonThrude** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#24]
![screenshot from 2017-11-20 12-41-24](https://user-images.githubusercontent.com/32300321/33016830-42aace9c-cdf0-11e7-8e4d-423c44e8991a.png)

**Comment by thejoeejoee** [comment]
Opraveno, zaktualizuj a vyzkoušej prosím. Jestli OK, zavři issue.
