### ISSUE TITLE
Windows - kódování souborů

### ISSUE THREAD

**Issue by moosejackson** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#25]
Diakritika v souborech uložené s kódováním UTF-8 se špatně zobrazuje. 
![image](https://user-images.githubusercontent.com/15686278/33075447-c72adf0c-cec9-11e7-8e89-e76f4a48ff5d.png)
Soubory musí být kódovány windows-1250, pak se to už zobrazuje dobře.

**Comment by SonyPony** [comment]
Python to špatně dělal, v Qt chyba není, Opraveno. @thejoeejoee udělá release.

// EDIT by @thejoeejoee: Špatně to v Pythonu dělal @SonyPony, ne Python.
// EDIT by @SonyPony: Windows za to může.

**Comment by thejoeejoee** [comment]
Releasnuto, @moosejackson zaktualizuj si prosím (`pip install --upgrade --no-cache-dir IFJcode17-toolkit`) a jestli je OK, zavři prosím.

**Comment by moosejackson** [comment]
super! už to je ok 👍 

//EDIT jen ta chyba, když se soubor otevírá s jiným kódováním než utf-8 je trochu zvláštní, IDE spadne a v konzoli je:

`Fatal: Traceback (most recent call last):
  File "C:\Users\Moose\AppData\Local\Programs\Python\Python36\lib\site-packages\ifj2017\ide\core\file_io.py", line 50, in read
    return str(read_data, encoding='utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 60: invalid start byte`
