### ISSUE TITLE
Testy bez označených rozšíření

### ISSUE THREAD

**Issue by timoti111** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#26]
Pre testy 02/12 a 02/20 treba rozšírenie FUNEXP.
Pre test 06/05 treba rozšírenie SCOPE.

**Comment by martinkobelka** [comment]
Mělo by být vyřešeno

**Comment by thejoeejoee** [comment]
Pardon @martinkobelka, moje chyba, měl jsem vysvětlit dříve. Považuji za standard, že issue zavírá zadávající, případně vedoucí projektu.
@timoti111 můžeš si prosím zkontrolovat?

**Comment by timoti111** [comment]
Je to v poriadku.

**Comment by timoti111** [comment]
Pre testy 02/12 a 02/20 treba rozšírenie FUNEXP.
Pre test 06/05 treba rozšírenie SCOPE.

**Comment by thejoeejoee** [comment]
Upraveno, s releasem si prosím vyzkoušej, @timoti111, pak zavři.

**Comment by thejoeejoee** [comment]
`1.2` je venku, vyzkoušej prosím

**Comment by timoti111** [comment]
Našiel som veľa ďalších prídam ich keď prídem domov. Poprípade ich môžem manuálne poupravovať cez PR.

**Comment by thejoeejoee** [comment]
Společně jste v #38 a #39 dořešili, díky moc!
Máte u mě pivo/kafe/žemli či hociaků čučorietku.
