### ISSUE TITLE
V IDE se započítává escape znak jako více znaků

### ISSUE THREAD

**Issue by moosejackson** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#29]
Pokud je string např. `x\032z` a chceme jeho délku, při použití fce strlen z IFJcode17 se do délky započítá i znak , který je escapovaný. Tzn. délka je 6 a ne 3. Na merlinovi to funguje jak má.

**Comment by thejoeejoee** [comment]
Opraveno, s releasem prosím vyzkoušej a jestli bude OK, zavři, díky.

**Comment by moosejackson** [comment]
Bohužel, stále nefunguje, délka je pořád 6 a ne 3 :/

**Comment by thejoeejoee** [comment]
Ale já ještě neudělal release, bude až v `> 1.1.9`.

**Comment by moosejackson** [comment]
moje chyba, promiň

**Comment by thejoeejoee** [comment]
tak už můžeš, `1.2` je venku

**Comment by moosejackson** [comment]
Funguje už, super 👍
