### ISSUE TITLE
Integrace s Google testy

### ISSUE THREAD

**Issue by SonyPony** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#3]
Vytvořit C++ třídu, která bude umět spustit takto definované testy pro snažší integraci s Google testy.

**Comment by thejoeejoee** [comment]
No a potřebujeme takovou integraci? Nestačilo by to spouštět prostě v rámci Travisu mimo GTest?

**Comment by SonyPony** [comment]
Ty jsi to prvně navrhoval :D

**Comment by thejoeejoee** [comment]
Tak to bylo prvotní, ale už jsem to napsal takhle, tak mi to přijde zbytečné, ne?

**Comment by SonyPony** [comment]
ok
