### ISSUE TITLE
Zlý očakávaný exit code

### ISSUE THREAD

**Issue by timoti111** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#33]
V teste 02/06 je očakávaný exit code 3 ale mal by byť 4:
```
• 3 - sémantická chyba v programu – nedefinovaná funkce/proměnná, pokus o redefinici funkce/proměnné, atd.
• 4 - sémantická chyba typové kompatibility v aritmetických, řetězcových a relačních
výrazech, příp. špatný počet či typ parametrů u volání funkce.
• 6 - ostatní sémantické chyby.
```

https://github.com/thejoeejoee/VUT-FIT-IFJ-2017-toolkit/blob/e3002ce6930df7d0efc5feb2c62826151fcc12cd/ifj2017/tests/02_functions/06.code#L1-L8

Názvy premenných možu byť rôzne:
```
Identifikátor formálního parametru v deklaraci funkce a v definici funkce se
může lišit, ale počty a typy parametrů musí souhlasit.
```

**Comment by thejoeejoee** [comment]
Ad test - netestuje názvy parametrů, ale jejich typy, viz druhý parametr `t as string` vs. `c as integer`.
Ad kód - je tam důležitý ten konec, **`špatný počet či typ parametrů u volání funkce`**. Nejedná se o volání funkce, pouze o její definici/deklaraci, proto čekáme `3`.
