### ISSUE TITLE
Ověření načítání standardního vstupu kompilátorem

### ISSUE THREAD

**Issue by kubiksamek** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#34]
Dovoluji si navrhnout test na správnost načítání zdrojového jazyka IFJ17 překladačem ifj.
Měli jsme problém, že nám Toolkit nechtěl pracovat tak jak by měl a vyhazoval chyby. Problém byl v tom, že my jsem soubor načítali z argumentu, ale správně má být ze STDIN. Když jsme testy pustili ručtě tak fungovali v pořádku. Bylo by fajn kdyby Toolkit fungoval tak i tak a jen na konci by např napsal, že se má načítat pouze ze STDIN. Jinak díky moc za Toolkit, super práce !!

**Comment by thejoeejoee** [comment]
Rozdělil bych na dvě části.
* **podpora dvou způsobů předání programu**
Proti tomuto se musím ohradit, ze zadání, cituji `Překladač bude načítat řídicí program v jazyce IFJ17 ze standardního vstupu a generovat výsledný mezikód v jazyce IFJcode17 (viz kapitola 10) na standardní výstup.` jasně plyne, že se musí jedna o program, který **konzumuje standardní vstup** a **produkuje standardní výstup**. Takovýmto chováním by šel spouštěč _proti zadání_ a to nechci. Ale můžeme se zeptat u @SonyPony, @martinkobelka nebo @timoti111, co na o říkají - za mě _ne_.

* **základní syntaktická kontrola `IFJcode17` před spuštěním interpretu**
Navrhuji přidat hlášku o nevalidním kódu v případě návratových kódů `51` a `52`, tedy syntaxe a základní sémantika. Chybu co nastala u @aliaCZEk by to zalogovalo jako nevalidní kód, nejen neshodu v návratovém kódu. 
P.S. vlastně by šel celý ten výčet  chyb interpretu mapovat na konkrétní hlášky
