### ISSUE TITLE
Snížení náročnosti 99/02

### ISSUE THREAD

**Issue by oberreiterm** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#36]
Fibonacciho posloupnost počítaná rekurzí má složitost O(2^N), tudíž při výpočtu `fib(25)` výpočet trvá neúměrně dlouho, a to hlavně díky verbose výstupu ic17int, jehož vypisování značně ovlivňuje rychlost.
Navrhuji snížit výpočet na `fib(10)`

**Comment by thejoeejoee** [comment]
Sníženo na `13`->` 144`, což je cenově desetina z 99/01. Vyzkoušej prosím u vás po releasu, jestli OK, zavři prosím.

**Comment by thejoeejoee** [comment]
`1.2` je venku, vyzkoušej prosím
