### ISSUE TITLE
Getchar ze string s escape sekvencí

### ISSUE THREAD

**Issue by SonyPony** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#37]
```
.IFJcode17

DEFVAR GF@text
DEFVAR GF@index
DEFVAR GF@single_char

MOVE GF@text string@\032
MOVE GF@index int@2
GETCHAR GF@single_char GF@text GF@index
write GF@single_char
```

Vypíše `2`, což znamená, že provádíš getchar i nad escape sekvencí(4 znaky), místo toho aby se brala jako jeden znak
EDIT: Zkontroluj si pro jistotu i #29

![](https://ctrlv.cz/shots/2017/11/23/85xu.png)

**Comment by thejoeejoee** [comment]
Opraveno ve `feature/escapes-solution`, ještě ji otestuji a půjde ven.
![image](https://user-images.githubusercontent.com/6154740/33243154-b5d269da-d2e0-11e7-9164-8744ab20eb6d.png)
