### ISSUE TITLE
Chybné testy

### ISSUE THREAD

**Issue by martinkobelka** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#4]
@thejoeejoee 
V testu 001_basic/03 jsou definovány proměnné typu float. Ty ale nás omezený free basic nepodporuje. Jen Integer , Double a String

V testu 002_functions/07 je návratový kód 3. Myslím že by měl být 4.

**Comment by thejoeejoee** [comment]
Obě po konzultacích opravené, díky za připomínky!
