### ISSUE TITLE
Chybné testy

### ISSUE THREAD

**Issue by oberreiterm** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#42]
V testech se vyskytuje několik nekorektních návratových kódů, špatně naspecifikovaných testů a i jeden bug.
Popis:
```
01_basic:
	016 (print string with char 238): ✓ × FAIL TO RUN INTERPRETER ('ascii' codec can't decode byte 0xee in position 0: ordinal not in range(128))
		- bug
02_functions:
	30  (multiple functions call): ✓✓ × STDOUT
		- poradi volani funkci neni definovane, proto by print nemel byt uvnitr funkce
04_expressions:
        27  (divide priority (fail types)):  × COMPILER EXIT CODE expected=4, returned=0
		- tohle ma fungovat a funguje i v fbc, protoze implicitni konverze
        28  (divide priority 2 (fail types)):  × COMPILER EXIT CODE expected=4, returned=2
		- ma fungovat, ale v testu u printu chybi strednik
        30  (divide priority 2 (fail types)):  × COMPILER EXIT CODE expected=4, returned=2
		- ma fungovat, ale v testu u printu chybi strednik
12_global:
        04  (global variable initialized from other global variable):  × COMPILER EXIT CODE expected=0, returned=6
		- nekonstantni definice globalni promenne - nelze ve FreeBASICu
        07  (global variable initialization by function call):  × COMPILER EXIT CODE expected=0, returned=6
		- nekonstantni definice globalni promenne - nelze ve FreeBASICu
        09  (static variable):  × COMPILER EXIT CODE expected=0, returned=6
		- nekonstantni definice globalni promenne - nelze ve FreeBASICu
        10  (multiple static variables):  × COMPILER EXIT CODE expected=0, returned=6
		- nekonstantni definice globalni promenne - nelze ve FreeBASICu
66_errors:
        083 (scope in function):  × COMPILER EXIT CODE expected=2, returned=0
		- povoleno v rozsireni SCOPE
99_benchmarks:
        07  (reference program working with strings and builtin functions): INTERPRETER TIMEOUT
		- test nema nadefinovany stdin a stdout, tudiz intepret cely cas ceka na stdin
	11  (big count of function parameters):  COMPILER TIMEOUT
		- je nutne zvednout timeout v tests.json, evidentne to vsem dela timeout
```

**Comment by thejoeejoee** [comment]
tak postupně
* `01/016` vím o tom, nedostal jsem se zatím k vyřešení
* `02/30` souhlas
* `04/27` z `100000\3/4\4\4/6` se vytváří dle priorit operátorů `100000\(3/4)\4\(4/6)`, výsledkem operátoru `/` je dle zadání vždy `Double` a operátor `\` přijímá pouze operandy typu `Integer`, tzn. typová chyba, za mě správně
* `04/28` středník souhlas, ale `10000000/3\4/4` jde na `(10000000/3)\(4/4)`, což je stejné jako test výše, typová chyba
* `04/30` středník souhlas, jinak opět typová chyba
* `12/*` za mě sporné, ale nejspíš máš pravdu, kromě chování fbc nevidím překážku, proč to neumět.
* `66/083` opraveno
* `99/07` přidán
* `99/11` přegenerováno na 50 parametrů

Změny rovnou vydány v `1.3.3`.

**Comment by oberreiterm** [comment]
@thejoeejoee
 `04/27`, `04/28`, `04/30` dle [dokumentace](https://www.freebasic.net/wiki/wikka.php?wakka=KeyPgOpIntegerDivide):

> Float numeric values are converted to Integer by rounding up or down, and the fractional part of the resulting quotient is truncated.

Tudíž by to mělo fungovat, nic o tom v nekompatibilitách na IFJ wiki není, tudíž to zřejmě máme podporovat.

`12/*`:  není to ani "podporované" FreeBASICem. [Dokumentace](https://www.freebasic.net/wiki/wikka.php?wakka=KeyPgShared) je v tomhle naprosto jednznačná:

> Shared variable may only be initialized with a constant value

**Comment by thejoeejoee** [comment]
Celočíselné v `04` opravené, release `1.3.5`.
Ad. `12/*` však jsem psal, že nevidím důvod to nepodporovat, možná nám to bude stát za dotaz na fórum.

**Comment by thejoeejoee** [comment]
Testy spoléhající na podporu přiřazení parametru při deklaraci statické proměnné odebrány & přidány testy na návratovou chybu 6 pro tyto případy.
@oberreiterm zkontroluješ si prosím po releasu `> 1.3.10`? díky!

**Comment by thejoeejoee** [comment]
pravděpodobně dořešeno, zavírám
