### ISSUE TITLE
Spouštění bez interpretace

### ISSUE THREAD

**Issue by kubiksamek** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#46]
Návrh pro přidání přepínače pro vypnutí interpretace.
Pro uživatele macOS velké +.
např: `--no-interpret` `-ni` `-mac` (:-))

**Comment by thejoeejoee** [comment]
Přidána podpora pro `--no-interpreter`, v tu chvíli se ani nekouká po `ic17int` a všechny testy jsou po zkontrolování návratového kódu kompilátoru za úspěšné.
Venku bude s `> 1.3.5`.

**Comment by thejoeejoee** [comment]
Releasnuto, vyzkoušej si a jestli OK, zavři prosím.

**Comment by kubiksamek** [comment]
OK, díky moc!
