### ISSUE TITLE
Bug při výpočtu ceny -  chyba interpretu

### ISSUE THREAD

**Issue by martinkobelka** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#47]
V testu 96_programs/11.code nastává bug při výpočtu ceny.
[https://github.com/thejoeejoee/VUT-FIT-IFJ-2017-toolkit/blob/master/ifj2017/tests/96_programs/11.code](https://github.com/thejoeejoee/VUT-FIT-IFJ-2017-toolkit/blob/master/ifj2017/tests/96_programs/11.code)

@thejoeejoee

**Comment by thejoeejoee** [comment]
`READ <symb> FLOAT` si neporadil s jednoduchým integerem typu `42`, opraveno.
