### ISSUE TITLE
ANSI znaky a barvičky nefungují na Ubuntu 16.04

### ISSUE THREAD

**Issue by Trsak** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#51]
Z nějakého důvodu mi na Ubuntu nefungují ANSI znaky, výstup pak vypadá dosti nehezky:
![https://ctrlv.cz/shots/2017/11/27/6lRA.png](https://ctrlv.cz/shots/2017/11/27/6lRA.png)

Nějaké nápady, co by za tím mohlo stát?

**Comment by thejoeejoee** [comment]
Co je to za příkazový interpreter, příp. jaká verze? je to výchozí *buntovský bash?
Ukážeš výstup z `locale` a `locale charmap`?

P.S. Barvy jdou dočasně vypnout pomocí `--no-colors`.

**Comment by Trsak** [comment]
![https://ctrlv.cz/shots/2017/11/28/xP71.png](https://ctrlv.cz/shots/2017/11/28/xP71.png)

**Comment by thejoeejoee** [comment]
To bude tím kódováním, `ISO-8859-1` si barvičkama a checkmarkama neporadí.
Když koukneš na `locale -a`, bylo by dobré si vybrat nějaké `en_US.utf8`, v `locale -m` potom `UTF-8` a [nastavit si je jako výchozí](https://askubuntu.com/a/193253), závislost na unicode shellu asi neodstraníme.

**Comment by Trsak** [comment]
Přechod na UTF-8 opravdu pomohl, díky

**Comment by thejoeejoee** [comment]
Nemáš zač, rád jsem pomohl.
