### ISSUE TITLE
Chybný test 99/03 hanoi tower

### ISSUE THREAD

**Issue by EnkeyMC** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#54]
V definici funkce hanoi je použit parametr `to`, což je ale při rozšíření CYCLES klíčové slovo. Překlad tudíž vrátí syntaktickou chybu.

**Comment by thejoeejoee** [comment]
Opraveno, s `> 1.4.1` bude nasazeno.

**Comment by thejoeejoee** [comment]
Myslím, že je již OK i nasazeno.
