### ISSUE TITLE
Test 04/27 - neměl by hodit chybu?

### ISSUE THREAD

**Issue by Trsak** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#55]
Podle mě by tento test měl vyhodit chybu:
`print 100000\(3/4)\4\(4/6);`

U operace \ musí být oba operandy typu integer, zde tomu tak není.

**Comment by thejoeejoee** [comment]
Řešili jsme v #42 a došli jsme, ze musí dojít k implicitním konverzím, zkus kouknout tam. Ale takhle si za tím stojíme.

**Comment by martinkobelka** [comment]
Free basic provádí implicitní konverze operandů vždy když je to potřeba a možné.

**Comment by Trsak** [comment]
Dle našeho názoru se jedná o další nekompatibilitu mezi jazyky.
Přece jen fbc umožňuje i něco takového:
```
Dim x as double = 15.3
DIM y as double = 3.6
DIM z as double
z = x \ y
print z;
```
 A to přímo odporuje zadání. Pokud nemáte nic proti, položím dotaz na forum.

**Comment by martinkobelka** [comment]
Ano to umožňuje,dá oba operandy na int a vypočítá výsledek který poté dá na double a uloží do z :) My to máme umět také. Vytvořil jsem podle tvého příkladu test do 04_expressions

**Comment by thejoeejoee** [comment]
Spíš si myslím, ze je to jen nešťastná formulace v zadani, kde se píše, ze se pracuje pouze s operandy typu Integer. To “pouze” dle mého navazuje na předchozí větu, která pojednává o nutné konverzi druhého operandu na double, v případě, ze jeden je taky double. 

Díky za to forum, uvidíme.

**Comment by Trsak** [comment]
Už tam máme odpověď - máte pravdu, konverze má proběhnout i zde 😃

**Comment by thejoeejoee** [comment]
Tím pádem vyřešeno, díky. Cituji odpověď z fóra od R. Kocmana:
```
Implicitní konverze jsou na hodnotu použity kdykoliv, je-li to potřeba.
Pokud operátor pracuje pouze s celými čísly, tak jsou na ně operandy
převedeny (je-li to možné). Stejně tak může být i výsledek operace
dále konvertován. Operátor by toto mohl ovlivnit pouze v případě, že
by přijímal i jiné typy a jejich kombinace by pak explicitně označoval za chybu.
```
