### ISSUE TITLE
Chyba chování GETCHAR

### ISSUE THREAD

**Issue by timoti111** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#56]
Interpreter berie ako chybu keď sa zavolá inštrukcia GETCHAR s parametrom prázdny reťazec a index 0.

**Comment by thejoeejoee** [comment]
jen si tu schovám, vrací správně 58
```
.IFJcode17

DEFVAR GF@a
GETCHAR GF@a string@ int@0
WRITE GF@a
```

**Comment by thejoeejoee** [comment]
Byla to chyba při volání `STRLEN`, která se projevila až špatným indexem zde. Opraveno v rámci #57.

Jestliže je OK, zavři prosím.
