### ISSUE TITLE
Špatné počítání ceny přístupu do paměti

### ISSUE THREAD

**Issue by jirvoz** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#57]
_Problém:_ nesouhlasí celková cena instrukcí interpretu tohoto projektu a referenčního interpretu z instrukcí BREAK nebo GROOT.

_Příčina:_ v interpretu tohoto projektu se špatně počítá cena přístupu do paměti (nejspíš nepřipočítává vůbec) a nerozlišuje tedy ceny přístupu ke konstantě, zásobníku a rámci.

**Comment by thejoeejoee** [comment]
Musím lehce poopravit, nepočítal se zápis do proměnné kromě deklarace, opravu mám, ještě musíme vymyslet jak distribuovat.

**Comment by thejoeejoee** [comment]
Opraveno, u proměnných se nepočítal jejich zápis & opraven `STRLEN`, co vždy vracel `2` od `v1.4`.
Navíc, před interpetací se vždy přidá `GROOT` a rozparzuje se jeho výsledek, který se následně porovná s vypočteným - jestliže nesouhlasí, je zalogováno.

Bude uvolněno nejspíše s `1.4.3`, ale nenapadá mě varianta, jak to provést bez znehodnocení vývojů cen.

Jestli je OK, zavři prosím.

**Comment by martinkobelka** [comment]
@thejoeejoee Do databáze by se dal přidat atribut, který říká že se jedná o neaktuální ceny Případně zvýšit koeficient o jaký se zvýšila cena a +- přepočítat. Případně ceny komplet přemazat.

Dobré by bylo, kdyby při odeslání hodnoty bylo známo z jaké verze byla poslána.
