### ISSUE TITLE
Mix variant definicie testov

### ISSUE THREAD

**Issue by WildBitangent** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#6]
Mozno by bolo prehladnejsie, aby sa mohol kod pre JSON nacitat z osobitneho suboru, radsej ako bol zapeceny priamo v JSONe.

**Comment by thejoeejoee** [comment]
Napadá mě trochu jednodušší varianta. V případě, že je ve složce soubor `tests.json` a u testu není v JSON definován `code`, hledá se automaticky soubor `<name>.code`. To stejné by platilo pro ostatní data, tedy návratové kódy kompilátoru, interpretu, standardního vstupu i výstupu. Co @SonyPony na to?

Pokud `tests.json` v sekci není, funguje vše dle souborů.

**Comment by thejoeejoee** [comment]
Naimplementoval jsem, @CaptainUnitato, koukneš na to? Je ti popsané i v github Wiki.

**Comment by thejoeejoee** [comment]
Dořešeno.
