### ISSUE TITLE
Chyba chování TYPE pro float

### ISSUE THREAD

**Issue by Trsak** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#64]
Například u následujícího kódu:
```
.IFJcode17
DEFVAR GF@typ
DEFVAR GF@promenna

MOVE GF@promenna int@5
TYPE GF@typ GF@promenna
JUMPIFNEQ konec GF@typ string@int

MOVE GF@promenna float@5.6
TYPE GF@typ GF@promenna
JUMPIFNEQ konec GF@typ string@float

WRITE string@SemByMelDojit

LABEL konec
```

Hodnoty `GF@typ` po druhém zavolání TYPE:
Value: None
Type: NoneType, 
měla by však obsahovat:
Value: float
Type: str.

Toto vede k chybě u výše uvedeného validního kodu:
`Undefined variable GF@typ on line 11: JUMPIFNEQ konec GF@typ string@float.`

**Comment by thejoeejoee** [comment]
![image](https://user-images.githubusercontent.com/6154740/33410994-3df10930-d583-11e7-81e1-feec82328021.png)

Důvodem nebylo druhé volání, ale `float`, který se musí kvůli možnému `%a` načítat odlišně, bude v `1.4.7`.

**Comment by thejoeejoee** [comment]
Je releasnuto v `1.4.7`.
