### ISSUE TITLE
Nazov parametru rovnaky ako nazov funkcie

### ISSUE THREAD

**Issue by simeonborko** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#68]
Myslim, ze test 66/21 je chybny, fbc na merlinovi ho prelozi bez chyby.

Nazov parametru nesmie byt rovnaky ako funkcia len v pripade, ze sa jedna o nazov parametru **v definicii**. V deklaracii moze byt nazov parametru lubovolny, aj rovnaky ako uz definovana funkcia.

**Comment by thejoeejoee** [comment]
Vycházeli jsme z odpovědi Z. Křivky na fóru, myslím, ze se jedná přesně o tento případ:
https://wis.fit.vutbr.cz/FIT/st/phorum-msg-show.php?id=49680&mode=mthr

4a) 
declare function foo1() as integer
declare function bar(foo1 as integer) as integer
Zde se jedná o chybu 3. Všimněte si ale, že ve FreeBASIC toto chyba není až do chvíle než funkci bar definujete. Ve FreeBASIC i IFJ17 ale máte možnost definovat funkci bar s jiným jménem parametru než bylo uvedeno v deklaraci. Nicméně v IFJ17 by toto nepomohlo na rozdíl od FreeBASIC.
