### ISSUE TITLE
Přidat testy i pro rozšíření

### ISSUE THREAD

**Issue by Trsak** [thejoeejoee/VUT-FIT-IFJ-2017-toolkit#9]
Zdravím,
vypadá to moc dobře, nevím kde na to berete tolik času 😄 

Jinak do budoucna by se určitě hodily i testy na rozšíření za prémiové body.

**Comment by thejoeejoee** [comment]
Zdravím, čas tak nějak extrahujeme z nezábavných projektů a spánku :smile: 

Už jsme nad tím přemýšleli a budeme muset vymyslet, jak jednotlivá rozšíření zapínat, protože ve výchozím stavu by nebylo dobré, aby se testovaly, když jsou dobrovolná.

**Comment by Trsak** [comment]
Ten kdo bude dělat rozšíření bude ve výsledků odevzdávat i soubor "rozsireni" na kterém budou na každém řádku uvedeny identifikátory implementovaných rozšíření.

Takže navrhuji přidat při spouštění testů nepovinný parametr, který bude obsahovat právě cestu k tomuto souboru.

**Comment by thejoeejoee** [comment]
@Trsak přidána možnost spouštění s cestou k souboru definující implementovaná rozšíření. Testy není mohou požadovat rozšíření, vše je popsáno ve Wiki na definici testů a argumentů příkazové řádky.
V tuto chvíli spouštím takto například:
```
thejoeejoee@selene:~/projects/VUT-FIT-IFJ-2017-tests$ python3 test.py --command-timeout 2 -e ~/projects/IFJ-VUT-BIT-2017-2018/rozsireni -v  ~/projects/IFJ-VUT-BIT-2017-2018/cmake-build-debug/ifj2017
```
